---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mojaloop-operator
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mojaloop-operator-cluster
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mojaloop-operator-cluster
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
subjects:
  - kind: ServiceAccount
    name: mojaloop-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: mojaloop-operator-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mojaloop-operator
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - mojaloop-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mojaloop-operator
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
subjects:
  - kind: ServiceAccount
    name: mojaloop-operator
roleRef:
  kind: Role
  name: mojaloop-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mojaloop-operator
  namespace: default
  labels:
    app.kubernetes.io/name: mojaloop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mojaloop-operator
  template:
    metadata:
      labels:
        name: mojaloop-operator
    spec:
      serviceAccountName: mojaloop-operator
      containers:
        - name: mojaloop-operator
          # Replace this with the built image name
          image: docker.io/matdabomb/ml-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mojaloop-operator"
